name: Build and release docs

on:
    release:
        types: [published]

jobs:
    build_deploy:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
              with:
                  persist-credentials: false

            - name: Install SSH Client 🔑
              uses: webfactory/ssh-agent@v0.4.1
              with:
                  ssh-private-key: ${{ secrets.DEPLOY_KEY }}
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: "12"

            - name: Install and build the documentation🔧
              run: |
                  npm install
                  npm link
                  npm run docs:refresh

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  BRANCH: docs
                  FOLDER: docs
                  SSH: true
